spring:
  datasource:
    url: jdbc:mysql://localhost:3307?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: member
    password: 1234
    schemas: ['member']

mybatis:
  mapper-locations: mapper/*.xml  # mapper/**/*.xml -> 폴더에 있을때
  configuration:
    map-underscore-to-camel-case: true